apiVersion: v2
name: ska-low
description: A Helm chart for Kubernetes MVP Low Notebooks
type: application
version: 0.0.1
appVersion: 0.0.1
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
  - name: ska-tango-base
    version: 0.4.10
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-tango-base.enabled
  - name: ska-tango-util
    version: 0.4.11
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-tango-util.enabled
  - name: ska-sdp
    version: 0.21.0
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-sdp.enabled
  - name: ska-tmc-low
    version: 0.18.1
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-tmc-low.enabled
    alias: tmc-low
  - name: ska-low-mccs
    version: 0.16.2
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-low-mccs.enabled
  - name: ska-csp-lmc-low
    version: 0.17.1
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-csp-lmc-low.enabled
  - name: ska-low-cbf
    version: 0.9.0
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-low-cbf.enabled
  - name: ska-low-cbf-proc
    version: 0.13.0
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-low-cbf-proc.enabled
  # - name: ska-low-cbf-tango-cnic
  #   version: 0.3.0
  #   repository:  https://artefact.skao.int/repository/helm-internal
  - name: ska-pst
    version: 0.12.1
    repository:  https://artefact.skao.int/repository/helm-internal
    condition: ska-pst.enabled
  - name: ska-tango-taranta
    version: 2.10.3
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled
    alias : ska-taranta
  - name: ska-tango-tangogql
    version: 1.4.4
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-tango-tangogql.enabled
  - name: ska-tango-taranta-auth
    version: 0.2.3
    repository: https://artefact.skao.int/repository/helm-internal
    condition: global.taranta_auth_enabled
  - name: ska-tango-taranta-dashboard
    version: 1.6.3
    repository: https://artefact.skao.int/repository/helm-internal
    condition: global.taranta_dashboard_enabled
  - name: ska-tango-taranta-dashboard-pvc
    version: 1.6.3
    repository: https://artefact.skao.int/repository/helm-internal
    condition: global.taranta_dashboard_enabled
  - name: ska-ser-skuid
    version: 3.3.3
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-ser-skuid.enabled