display: ":0"
xauthority: "~/.Xauthority"

global:
  labels:
    app: ska-jupyter-scripting
  minikube: false
  operator: true
  exposeAllDS: false
  taranta_auth_enabled: false
  taranta_dashboard_enabled: true
  annotations:
    app.gitlab.com/app: ska-jupyter-scripting
    app.gitlab.com/env: ska-low
  sub-system:
    tango-base:
      enabled: false
    ska-tango-base:
      enabled: false
    ska-taranta:
      enabled: false
  retry:
    - "--sleep=1"
    - "--tries=100"
  tango_host: databaseds:10000
  device_server_port: 45450
  cluster_domain: techops.internal.skao.int
  data-product-pvc-name: shared
  dsconfig:
    timeout: 300s
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-dsconfig
      tag: 1.5.1
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-itango
      tag: 9.3.5
      pullPolicy: IfNotPresent
  tango_example:
    image:
      registry: harbor.skao.int/production
      image: ska-tango-examples
      tag: 0.4.32
      pullPolicy: IfNotPresent

ska-tango-base:
  enabled: true
  vnc:
    replicas: 1
    enabled: true
  tangorest:
    replicas: 1
    enabled: true
    resources:
      requests:
        cpu: 100m # 100m = 0.1 CPU
        memory: 128Mi # 256Mi = 0.25 GB mem
        ephemeral-storage: 256Mi
      limits:
        cpu: 200m # 100m = 0.1 CPU
        memory: 768Mi # 256Mi = 0.25 GB mem
        ephemeral-storage: 256Mi
  tangotest:
    enabled: true
  ingress:
    enabled: true
    hostname: k8s.stfc.skao.int
  tangodb:
    use_pv: false

#=== OSO ===#    

#=== MCCS ===#
ska-low-mccs:
  enabled: true
  labels:
    app: ska-low-integration
    
  ska-low-mccs-pasd:
    enabled: true

  ska-low-mccs-spshw:
    enabled: true

    ska-low-mccs-daq:
      enabled: true

#=== CSP ===#
ska-csp-lmc-low:
  labels:
    app: ska-jupyter-scripting
  enabled: true
  
#=== LOW CBF ===#
ska-low-cbf:
    enabled: true
    minikube: true
    labels:
      app: ska-jupyter-scripting
    cbf:
      hardware_connections:
        # psi-perentie1
        - 'switch=p4_01  port=19/0  speed=100  alveo=XFL14SLO1LIF'
        - 'switch=p4_01  port=21/0  speed=100  alveo=XFL1DKXBEVG2'
        - 'switch=p4_01  port=23/0  speed=100  alveo=XFL1HOOQ1Y44'
        - 'switch=p4_01  port=25/0  speed=100  alveo=XFL1LHN4TXO2'

ska-low-cbf-tango-cnic:
  enabled: false

ska-low-cbf-proc:
  deviceServers:
    processor:
      instances: ["0", "1"] 
      resources:
        limits:
          amd.com/xilinx_u55c_gen3x16_xdma_base_3-0: 0  # no FPGA hardware
          memory: 512Mi  # reduced

#=== PST ===#
ska-pst:
  enabled: true
  ska-pst-core:
    enabled: false
    serviceAccount:
      create: false
    send:
      enabled: true
      dpdApiIntegration: true

  ska-pst-jupyterlab:
    enabled: false

  ska-pst-lmc:
    enabled: true
    beam:
      simulationMode: 1
      scanOutputDirPattern: /tmp/<eb_id>/<subsystem_id>/<scan_id>

    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution: []

  volume: null

#=== SDP ===#
ska-sdp:
  labels:
    app: ska-jupyter-scripting
  ska-tango-base:
    enabled: false
  lmc:
    prefix: low
    nsubarray: 3
  data-pvc:
    create:
      enabled: true
      size: 20Gi
      storageClassName: nfss1

#=== TMC LOW ===#
ska-tmc-low:
  enabled: true

## tmc-low
tmc-low:
  enabled: true
  legacy_compatibility: true
  telescope: SKA-low
  ska-tango-base:
    enabled: false
  deviceServers:
    mocks:
      enabled: false
      is_simulated:
        mccs: false
        csp: false
        sdp: false

ska-taranta:
  enabled: true
  basename: true

#=== Taranta ===#
ska-tango-tangogql:
  enabled: true
  ska-tango-base:
    enabled: false
  basename: true
  