display: ":0"
xauthority: "~/.Xauthority"

global:
  labels:
    app: ska-low-integration
  minikube: false
  operator: true
  exposeAllDS: false
  taranta_auth_enabled: false
  taranta_dashboard_enabled: false
  environment_variables: 
    - name: NO_HEALTH_ROLLUP
      value: "unused_value"
    - name: PROCESSOR_WAIT_QTY
      value: "none"
    - name: PROCESSOR_WAIT_SECS
      value: '"10"'
    - name: ALLOW_AUTO_REGISTER_PROCESSORS
      value: "unused_value"
  annotations:
    app.gitlab.com/app: ska-low-integration
    app.gitlab.com/env: ska-low
  sub-system:
    tango-base:
      enabled: false
    ska-tango-base:
      enabled: false
    ska-taranta:
      enabled: false
  retry:
    - "--sleep=1"
    - "--tries=100"
  tango_host: databaseds:10000
  device_server_port: 45450
  cluster_domain: techops.internal.skao.int
  data-product-pvc-name: shared
  dsconfig:
    timeout: 300s
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-dsconfig
      tag: 1.5.1
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-itango
      tag: 9.3.10
      pullPolicy: IfNotPresent
  tango_example:
    image:
      registry: harbor.skao.int/production
      image: ska-tango-examples
      tag: 0.4.32
      pullPolicy: IfNotPresent

ska-tango-base:
  enabled: true
  vnc:
    replicas: 1
    enabled: true
  tangorest:
    replicas: 1
    enabled: true
    resources:
      requests:
        cpu: 100m # 100m = 0.1 CPU
        memory: 128Mi # 256Mi = 0.25 GB mem
        ephemeral-storage: 256Mi
      limits:
        cpu: 200m # 100m = 0.1 CPU
        memory: 768Mi # 256Mi = 0.25 GB mem
        ephemeral-storage: 256Mi
  tangotest:
    enabled: true
  ingress:
    enabled: true
    hostname: k8s.stfc.skao.int
  tangodb:
    use_pv: false

#=== OSO ===#

#=== MCCS ===#
ska-low-mccs:
  labels:
    app: ska-low-integration
  legacy_compatibility: true
  enabled: true
  daqDataRepository: daq-data
  deviceServers:
    calibrationstores:
      ci-1:
        low-mccs/calibrationstore/ci-1:
          logging_level_default: 5
      ci-2:
        low-mccs/calibrationstore/ci-2:
          logging_level_default: 5
    controllers:
      controller:
        low-mccs/control/control:
          stationbeams:
          - low-mccs/beam/ci-1-01
          - low-mccs/beam/ci-2-01
          stations:
          - low-mccs/station/ci-1
          - low-mccs/station/ci-2
          subarraybeams:
          - low-mccs/subarraybeam/01
          subarrays:
          - low-mccs/subarray/01
    solvers:
      ci-1:
        low-mccs/solver/ci-1:
          eep_root_path: /app/tests/unit/calibration_solver/testing_data
          logging_level_default: 5
          root_path: /app/tests/unit/calibration_solver/testing_data
      ci-2:
        low-mccs/solver/ci-2:
          eep_root_path: /eep-data
          logging_level_default: 5
          root_path: /daq-data
    stationbeams:
      stationbeams-ci-1:
        low-mccs/beam/ci-1-01:
          beam_id: 1
      stationbeams-ci-2:
        low-mccs/beam/ci-2-01:
          beam_id: 49
    stationcalibrators:
      ci-1:
        low-mccs/stationcalibrator/ci-1:
          calibration_solver_trl: low-mccs/solver/ci-1
          calibration_store_trl: low-mccs/calibrationstore/ci-1
          logging_level_default: 5
          station_id: 1
          station_trl: low-mccs/station/ci-1
      ci-2:
        low-mccs/stationcalibrator/ci-2:
          calibration_solver_trl: low-mccs/solver/ci-2
          calibration_store_trl: low-mccs/calibrationstore/ci-2
          logging_level_default: 5
          station_id: 2
          station_trl: low-mccs/station/ci-2
    stations:
      station-ci-1:
        low-mccs/station/ci-1:
          field_station_trl: low-mccs/fieldstation/ci-1
          logging_level_default: 5
          ref_height: 1
          ref_latitude: -1
          ref_longitude: 1
          sps_station_trl: low-mccs/spsstation/ci-1
          station_calibrator_trl: low-mccs/stationcalibrator/ci-1
          station_id: 1
      station-ci-2:
        low-mccs/station/ci-2:
          field_station_trl: low-mccs/fieldstation/ci-2
          logging_level_default: 5
          ref_height: 0
          ref_latitude: 0
          ref_longitude: 0
          sps_station_trl: low-mccs/spsstation/ci-2
          station_calibrator_trl: low-mccs/stationcalibrator/ci-2
          station_id: 2
    subarraybeams:
      subarraybeam-01:
        low-mccs/subarraybeam/01:
          logging_level_default: 5
    subarrays:
      subarray-01:
        low-mccs/subarray/01:
          logging_level_default: 5
          skuid_url: http://ska-ser-skuid-ska-ser-skuid-svc:9870/
          subarray_id: 1
  ska-low-mccs-pasd:
    configServers:
      array:
        host: pasd-configuration-service
        port: 8081
    deviceServers:
      fieldstation-ci-1:
        devices:
          MccsFieldStation:
            low-mccs/fieldstation/ci-1:
              ConfigurationHost: pasd-configuration-service
              ConfigurationPort: 8081
              FndhFQDN: low-mccs/fndh/ci-1
              LoggingLevelDefault: 5
              SmartBoxFQDNs:
              - low-mccs/smartbox/ci-1-sb01
              StationName: ci-1
        expose: true
      fieldstation-ci-2:
        devices:
          MccsFieldStation:
            low-mccs/fieldstation/ci-2:
              ConfigurationHost: pasd-configuration-service
              ConfigurationPort: 8081
              FndhFQDN: low-mccs/fndh/ci-2
              LoggingLevelDefault: 5
              SmartBoxFQDNs:
              - low-mccs/smartbox/ci-2-sb01
              StationName: ci-2
        expose: true
      fndh-ci-1:
        depends_on:
        - device: low-mccs/pasdbus/ci-1
        devices:
          MccsFNDH:
            low-mccs/fndh/ci-1:
              LoggingLevelDefault: 5
              PasdFQDN: low-mccs/pasdbus/ci-1
      fndh-ci-2:
        depends_on:
        - device: low-mccs/pasdbus/ci-2
        devices:
          MccsFNDH:
            low-mccs/fndh/ci-2:
              LoggingLevelDefault: 5
              PasdFQDN: low-mccs/pasdbus/ci-2
      pasdbus-ci-1:
        devices:
          MccsPasdBus:
            low-mccs/pasdbus/ci-1:
              AvailableSmartboxes:
              - 1
              DevicePollingRate: 3
              Host: pasd-simulator-ci-1
              LoggingLevelDefault: 5
              PollingRate: 0.2
              Port: 9502
              SimulationConfig: 1
              Timeout: 10
      pasdbus-ci-2:
        devices:
          MccsPasdBus:
            low-mccs/pasdbus/ci-2:
              AvailableSmartboxes:
              - 1
              DevicePollingRate: 3
              Host: pasd-simulator-ci-2
              LoggingLevelDefault: 5
              PollingRate: 0.2
              Port: 9502
              SimulationConfig: 1
              Timeout: 10
      smartbox-ci-1-sb01:
        depends_on:
        - device: low-mccs/pasdbus/ci-1
        devices:
          MccsSmartbox:
            low-mccs/smartbox/ci-1-sb01:
              FieldStationName: low-mccs/fieldstation/ci-1
              FndhFQDN: low-mccs/fndh/ci-1
              LoggingLevelDefault: 5
              PasdFQDN: low-mccs/pasdbus/ci-1
              SmartboxNumber: 1
      smartbox-ci-2-sb01:
        depends_on:
        - device: low-mccs/pasdbus/ci-2
        devices:
          MccsSmartbox:
            low-mccs/smartbox/ci-2-sb01:
              FieldStationName: low-mccs/fieldstation/ci-2
              FndhFQDN: low-mccs/fndh/ci-2
              LoggingLevelDefault: 5
              PasdFQDN: low-mccs/pasdbus/ci-2
              SmartboxNumber: 1
    referenceData:
      pasdconfiguration:
        ci-1:
          antennas:
            sb01-01:
              masked: false
              smartbox: sb01
              smartbox_port: 1
            sb01-02:
              masked: false
              smartbox: sb01
              smartbox_port: 2
            sb01-03:
              masked: false
              smartbox: sb01
              smartbox_port: 3
            sb01-04:
              masked: false
              smartbox: sb01
              smartbox_port: 4
            sb01-05:
              masked: false
              smartbox: sb01
              smartbox_port: 5
            sb01-06:
              masked: false
              smartbox: sb01
              smartbox_port: 6
            sb01-07:
              masked: false
              smartbox: sb01
              smartbox_port: 7
            sb01-08:
              masked: false
              smartbox: sb01
              smartbox_port: 8
            sb01-09:
              masked: false
              smartbox: sb01
              smartbox_port: 9
            sb01-10:
              masked: false
              smartbox: sb01
              smartbox_port: 10
          pasd:
            smartboxes:
              sb01:
                fndh_port: 1
        ci-2:
          antennas:
            sb01-01:
              masked: false
              smartbox: sb01
              smartbox_port: 1
            sb01-02:
              masked: false
              smartbox: sb01
              smartbox_port: 2
            sb01-03:
              masked: false
              smartbox: sb01
              smartbox_port: 3
            sb01-04:
              masked: false
              smartbox: sb01
              smartbox_port: 4
            sb01-05:
              masked: false
              smartbox: sb01
              smartbox_port: 5
            sb01-06:
              masked: false
              smartbox: sb01
              smartbox_port: 6
            sb01-07:
              masked: false
              smartbox: sb01
              smartbox_port: 7
            sb01-08:
              masked: false
              smartbox: sb01
              smartbox_port: 8
            sb01-09:
              masked: false
              smartbox: sb01
              smartbox_port: 9
            sb01-10:
              masked: false
              smartbox: sb01
              smartbox_port: 10
          pasd:
            smartboxes:
              sb01:
                fndh_port: 1
    simulators:
      pasdbuses:
        ci-1:
          host: pasd-simulator-ci-1
          port: 9502
        ci-2:
          host: pasd-simulator-ci-2
          port: 9502
  ska-low-mccs-spshw:
    deviceServers:
      daqs:
        ci-1:
          low-mccs/daqreceiver/ci-1:
            host: daqrx-ci-1
            id: 1
            logging_level_default: 5
            port: 50051
            skuid_url: http://ska-ser-skuid-ska-ser-skuid-svc:9870/
        ci-1-bandpass:
          low-mccs/daqreceiver/ci-1-bandpass:
            host: daqrx-ci-1-bandpass
            id: 1
            logging_level_default: 5
            port: 50051
            skuid_url: http://ska-ser-skuid-ska-ser-skuid-svc:9870/
        ci-2:
          low-mccs/daqreceiver/ci-2:
            host: daqrx-ci-2
            id: 2
            logging_level_default: 5
            port: 50051
            skuid_url: http://ska-ser-skuid-ska-ser-skuid-svc:9870/
        ci-2-bandpass:
          low-mccs/daqreceiver/ci-2-bandpass:
            host: daqrx-ci-2-bandpass
            id: 2
            logging_level_default: 5
            port: 50051
            skuid_url: http://ska-ser-skuid-ska-ser-skuid-svc:9870/
      spsstations:
        ci-1:
          low-mccs/spsstation/ci-1:
            antenna_config_uri: []
            csp_rounding: 2
            daq_trl: low-mccs/daqreceiver/ci-1
            logging_level_default: 5
            sdn_first_interface: 10.0.0.128/16
            station_id: 1
            subracks:
            - low-mccs/subrack/ci-1-sr1
            tpms:
            - low-mccs/tile/ci-1-tpm01
        ci-2:
          low-mccs/spsstation/ci-2:
            antenna_config_uri: []
            csp_rounding: 2
            daq_trl: low-mccs/daqreceiver/ci-2
            logging_level_default: 5
            sdn_first_interface: 10.0.0.192/16
            station_id: 2
            subracks:
            - low-mccs/subrack/ci-2-sr1
            tpms:
            - low-mccs/tile/ci-2-tpm01
      subracks:
        ci-1-sr1:
          low-mccs/subrack/ci-1-sr1:
            logging_level_default: 5
            srmb_host: subrack-simulator-ci-1-sr1
            srmb_port: 8081
        ci-2-sr1:
          low-mccs/subrack/ci-2-sr1:
            logging_level_default: 5
            srmb_host: subrack-simulator-ci-2-sr1
            srmb_port: 8081
      tpms:
        ci-1-tpm01:
          low-mccs/tile/ci-1-tpm01:
            host: 10.0.10.201
            logging_level_default: 5
            port: 10000
            simulation_config: 1
            station_id: 1
            subrack: ci-1-sr1
            subrack_slot: 1
            test_config: 1
            tile_id: 0
            version: tpm_v1_6
        ci-2-tpm01:
          low-mccs/tile/ci-2-tpm01:
            host: 10.0.10.201
            logging_level_default: 5
            port: 10000
            simulation_config: 1
            station_id: 2
            subrack: ci-2-sr1
            subrack_slot: 1
            test_config: 1
            tile_id: 0
            version: tpm_v1_6
    simulators:
      subracks:
        ci-1-sr1:
          srmb_host: subrack-simulator-ci-1-sr1
          srmb_port: 8081
        ci-2-sr1:
          srmb_host: subrack-simulator-ci-2-sr1
          srmb_port: 8081
    ska-low-mccs-daq:
      receivers:
        ci-1:
          affinity: null
          grpc_port: 50051
          node_selector: null
          nvidia_gpu: false
          receiver_interface: eth0
          receiver_port: 4660
          storage: daq-data
          tolerations: null
        ci-1-bandpass:
          affinity: null
          expose_data_service: true
          grpc_port: 50051
          node_selector: null
          nvidia_gpu: false
          receiver_interface: eth0
          receiver_port: 4660
          resources:
            limits:
              memory: 4G
          tolerations: null
        ci-2:
          affinity: null
          grpc_port: 50051
          node_selector: null
          nvidia_gpu: false
          receiver_interface: eth0
          receiver_port: 4660
          storage: daq-data
          tolerations: null
        ci-2-bandpass:
          affinity: null
          expose_data_service: true
          grpc_port: 50051
          node_selector: null
          nvidia_gpu: false
          receiver_interface: eth0
          receiver_port: 4660
          resources:
            limits:
              memory: 4G
          tolerations: null
      storage:
        daq-data:
          size: 250Mi
          storage_class: nfss1

#=== CSP ===#
ska-csp-lmc-low:
  labels:
    app: ska-low-integration
  enabled: true

#=== LOW CBF ===#
ska-low-cbf:
    enabled: true
    minikube: true
    labels:
      app: ska-low-integration
    cbf:
      hardware_connections:
        # psi-perentie1
        - 'switch=p4_01  port=19/0  speed=100  alveo=XFL14SLO1LIF'
        - 'switch=p4_01  port=21/0  speed=100  alveo=XFL1DKXBEVG2'
        - 'switch=p4_01  port=23/0  speed=100  alveo=XFL1HOOQ1Y44'
        - 'switch=p4_01  port=25/0  speed=100  alveo=XFL1LHN4TXO2'

ska-low-cbf-tango-cnic:
  enabled: false

ska-low-cbf-proc:
  deviceServers:
    processor:
      instances: ["0", "1"]
      resources:
        limits:
          amd.com/xilinx_u55c_gen3x16_xdma_base_3-0: 0  # no FPGA hardware
          memory: 512Mi  # reduced

#=== PST ===#
ska-pst:
  enabled: true
  core:
    enabled: false
    send:
      enabled: true
      dpdApiIntegration: true

  ska-pst-jupyterlab:
    enabled: false

  deviceServers:
    pstLmc:
      enabled: true
      simulationMode: 1
      # scanOutputDirPattern: /tmp/<eb_id>/<subsystem_id>/<scan_id>

  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: []

  #volume: null

#=== SDP ===#
ska-sdp:
  labels:
    app: ska-low-integration
  ska-tango-base:
    enabled: false
  lmc:
    prefix: low
    nsubarray: 3
  data-pvc:
    create:
      enabled: true
      size: 20Gi
      storageClassName: nfss1

#=== TMC LOW ===#
ska-tmc-low:
  enabled: true
  subarraynode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-subarraynode
    tag: 0.30.1-dev.c9eefd3e6
    pullPolicy: IfNotPresent


## tmc-low
tmc-low:
  enabled: true
  legacy_compatibility: true
  telescope: SKA-low
  ska-tango-base:
    enabled: false
  deviceServers:
    mocks:
      enabled: false
      is_simulated:
        mccs: false
        csp: false
        sdp: false

ska-taranta:
  enabled: true

#=== Taranta ===#
ska-tango-tangogql:
  enabled: true
  ska-tango-base:
    enabled: false

#=== EDA ===#
ska-tango-archiver:
  #hostname: eda.ska-tango-archiver - Updating this from Makefile
  dbname: low_sw_integration_eda
  dbuser: admin
  # dbpassword - this is set from the pipeline
  port: 5432
  telescope: SKA-low
  telescope-environment: LOW-STFC
  # archwizard_config: MyHDB=tango://tango-databaseds.test-environment.svc.lowitf.internal.skao.int:10000/low-eda/cm/01 - Updating this from Makefile
