global:
  taranta_dashboard_enabled: false
  taranta_auth_enabled: false

tmc-low:
  enabled: true
  deviceServers:
    mocks:
      enabled: true
      is_simulated:
        csp: true
        sdp: false
        mccs: true
        

ska-sdp:
  labels:
    app: ska-low-integration
  legacy_compatibility: true
  enabled: true
  lmc:
    loadBalancer: true
    prefix: low
    nsubarray: 1
  console:
    enabled: true
  ska-sdp-qa:
    kafka:
      resources:
        limits:
          memory: 100Mi
        requests:
          cpu: 100m
          memory: 50Mi
      livenessProbe:
        initialDelaySeconds: 30
        failureThreshold: 5
      zookeeper:
        resources:
          requests:
            cpu: 100m
  ska-tango-base:
    enabled: false
  
  
ska-taranta:
  enabled : false 
  
ska-low-cbf:
  enabled: false

ska-pst-lmc:
  enabled: false

ska-pst:
  enabled: false

ska-csp-lmc-low:
  enabled : false
  
ska-ser-skuid:
  enabled : false

ska-low-mccs:
  enabled: false

ska-low-cbf-proc:
  enabled: false