

tmc-low:
  enabled: true
  deviceServers:
    mocks:
      enabled: true
      is_simulated:
        mccs: false
        csp: true
        sdp: true

ska-tango-base:
  enabled: true 
      
ska-low-mccs:
  labels:
    app: ska-low-integration
  legacy_compatibility: true
  enabled: true
  daqDataRepository: daq-data
  deviceServers:
    antennas:
      antennas-ci-1:
        low-mccs/antenna/ci-1-sb01-01:
          antenna_id: 244
          field_station_trl: low-mccs/fieldstation/ci-1
          logging_level_default: 5
          tile_trl: low-mccs/tile/ci-1-tpm01
          tile_x_channel: 31
          tile_y_channel: 30
          x_displacement: -5.422
          y_displacement: 17.79
          z_displacement: 0.008
      antennas-ci-2:
        low-mccs/antenna/ci-2-sb01-01:
          antenna_id: 244
          field_station_trl: low-mccs/fieldstation/ci-2
          logging_level_default: 5
          tile_trl: low-mccs/tile/ci-2-tpm01
          tile_x_channel: 31
          tile_y_channel: 30
          x_displacement: -5.422
          y_displacement: 17.79
          z_displacement: 0.008
    cabinetbanks:
      cabinetbank-cb-1:
        low-mccs/cabinetbank/cb-1:
          cabinetbank_id: 1
          stations:
          - low-mccs/station/ci-1
          - low-mccs/station/ci-2
    calibrationstores:
      ci-1:
        low-mccs/calibrationstore/ci-1:
          logging_level_default: 5
      ci-2:
        low-mccs/calibrationstore/ci-2:
          logging_level_default: 5
    controllers:
      controller:
        low-mccs/control/control:
          cabinetbanks:
          - low-mccs/cabinetbank/cb-1
          stationbeams:
          - low-mccs/beam/ci-1-01
          - low-mccs/beam/ci-2-01
          stations:
          - low-mccs/station/ci-1
          - low-mccs/station/ci-2
          subarraybeams:
          - low-mccs/subarraybeam/01
          subarrays:
          - low-mccs/subarray/01
    solvers:
      ci-1:
        low-mccs/solver/ci-1:
          eep_root_path: /app/tests/unit/calibration_solver/testing_data
          logging_level_default: 5
          root_path: /app/tests/unit/calibration_solver/testing_data
      ci-2:
        low-mccs/solver/ci-2:
          eep_root_path: /eep-data
          logging_level_default: 5
          root_path: /daq-data
    stationbeams:
      stationbeams-ci-1:
        low-mccs/beam/ci-1-01:
          beam_id: 1
      stationbeams-ci-2:
        low-mccs/beam/ci-2-01:
          beam_id: 49
    stationcalibrators:
      ci-1:
        low-mccs/stationcalibrator/ci-1:
          calibration_solver_trl: low-mccs/solver/solver-ci-1
          calibration_store_trl: low-mccs/calibrationstore/ci-1
          logging_level_default: 5
          station_trl: low-mccs/station/ci-1
      ci-2:
        low-mccs/stationcalibrator/ci-2:
          calibration_solver_trl: low-mccs/solver/solver-ci-2
          calibration_store_trl: low-mccs/calibrationstore/ci-2
          logging_level_default: 5
          station_trl: low-mccs/station/ci-2
    stations:
      station-ci-1:
        low-mccs/station/ci-1:
          antenna_ids:
          - 244
          antenna_trls:
          - low-mccs/antenna/ci-1-sb01-01
          antenna_xs:
          - -5.422
          antenna_ys:
          - 17.79
          antenna_zs:
          - 0.008
          field_station_trl: low-mccs/fieldstation/ci-1
          logging_level_default: 5
          ref_height: 1
          ref_latitude: -1
          ref_longitude: 1
          sps_station_trl: low-mccs/spsstation/ci-1
          station_calibrator_trl: low-mccs/stationcalibrator/ci-1
          station_id: 1
      station-ci-2:
        low-mccs/station/ci-2:
          antenna_ids:
          - 244
          antenna_trls:
          - low-mccs/antenna/ci-2-sb01-01
          antenna_xs:
          - -5.422
          antenna_ys:
          - 17.79
          antenna_zs:
          - 0.008
          field_station_trl: low-mccs/fieldstation/ci-2
          logging_level_default: 5
          ref_height: 0
          ref_latitude: 0
          ref_longitude: 0
          sps_station_trl: low-mccs/spsstation/ci-2
          station_calibrator_trl: low-mccs/stationcalibrator/ci-2
          station_id: 2
    subarraybeams:
      subarraybeam-01:
        low-mccs/subarraybeam/01:
          logging_level_default: 5
    subarrays:
      subarray-01:
        low-mccs/subarray/01:
          logging_level_default: 5
          skuid_url: http://ska-ser-skuid-ska-ser-skuid-svc:9870/
          subarray_id: 1
  global:
    cluster_domain: techops.internal.skao.int
    minikube: true
    tango_host: databaseds-tango-base:10000
  ska-low-mccs-pasd:
    configServers:
      array:
        host: pasd-configuration-service
        port: 8081
    deviceServers:
      fieldstations:
        ci-1:
          low-mccs/fieldstation/ci-1:
            configuration_host: pasd-configuration-service
            configuration_port: 8081
            fndh_name: low-mccs/fndh/ci-1
            logging_level_default: 5
            smartbox_names:
            - low-mccs/smartbox/ci-1-sb01
        ci-2:
          low-mccs/fieldstation/ci-2:
            configuration_host: pasd-configuration-service
            configuration_port: 8081
            fndh_name: low-mccs/fndh/ci-2
            logging_level_default: 5
            smartbox_names:
            - low-mccs/smartbox/ci-2-sb01
      fndhs:
        ci-1:
          low-mccs/fndh/ci-1:
            logging_level_default: 5
            pasdbus_name: low-mccs/pasdbus/ci-1
        ci-2:
          low-mccs/fndh/ci-2:
            logging_level_default: 5
            pasdbus_name: low-mccs/pasdbus/ci-2
      pasdbuses:
        ci-1:
          low-mccs/pasdbus/ci-1:
            device_polling_rate: 3
            host: pasd-simulator-ci-1
            logging_level_default: 5
            polling_rate: 0.2
            port: 9502
            simulation_config: 1
            timeout: 10
        ci-2:
          low-mccs/pasdbus/ci-2:
            device_polling_rate: 3
            host: pasd-simulator-ci-2
            logging_level_default: 5
            polling_rate: 0.2
            port: 9502
            simulation_config: 1
            timeout: 10
      smartboxes:
        ci-1-sb01:
          low-mccs/smartbox/ci-1-sb01:
            field_station_name: low-mccs/fieldstation/ci-1
            fndh_name: low-mccs/fndh/ci-1
            fndh_port: 1
            logging_level_default: 5
            pasdbus_name: low-mccs/pasdbus/ci-1
            smartbox_number: 1
        ci-2-sb01:
          low-mccs/smartbox/ci-2-sb01:
            field_station_name: low-mccs/fieldstation/ci-2
            fndh_name: low-mccs/fndh/ci-2
            fndh_port: 1
            logging_level_default: 5
            pasdbus_name: low-mccs/pasdbus/ci-2
            smartbox_number: 1
    referenceData:
      pasdconfiguration:
        ci-1:
          antennas:
            sb01-01:
              masked: false
              smartbox: sb01
              smartbox_port: 1
            sb01-02:
              masked: false
              smartbox: sb01
              smartbox_port: 2
            sb01-03:
              masked: false
              smartbox: sb01
              smartbox_port: 3
            sb01-04:
              masked: false
              smartbox: sb01
              smartbox_port: 4
            sb01-05:
              masked: false
              smartbox: sb01
              smartbox_port: 5
            sb01-06:
              masked: false
              smartbox: sb01
              smartbox_port: 6
            sb01-07:
              masked: false
              smartbox: sb01
              smartbox_port: 7
            sb01-08:
              masked: false
              smartbox: sb01
              smartbox_port: 8
            sb01-09:
              masked: false
              smartbox: sb01
              smartbox_port: 9
            sb01-10:
              masked: false
              smartbox: sb01
              smartbox_port: 10
          pasd:
            smartboxes:
              sb01:
                fndh_port: 1
        ci-2:
          antennas:
            sb01-01:
              masked: false
              smartbox: sb01
              smartbox_port: 1
            sb01-02:
              masked: false
              smartbox: sb01
              smartbox_port: 2
            sb01-03:
              masked: false
              smartbox: sb01
              smartbox_port: 3
            sb01-04:
              masked: false
              smartbox: sb01
              smartbox_port: 4
            sb01-05:
              masked: false
              smartbox: sb01
              smartbox_port: 5
            sb01-06:
              masked: false
              smartbox: sb01
              smartbox_port: 6
            sb01-07:
              masked: false
              smartbox: sb01
              smartbox_port: 7
            sb01-08:
              masked: false
              smartbox: sb01
              smartbox_port: 8
            sb01-09:
              masked: false
              smartbox: sb01
              smartbox_port: 9
            sb01-10:
              masked: false
              smartbox: sb01
              smartbox_port: 10
          pasd:
            smartboxes:
              sb01:
                fndh_port: 1
    simulators:
      pasdbuses:
        ci-1:
          host: pasd-simulator-ci-1
          port: 9502
        ci-2:
          host: pasd-simulator-ci-2
          port: 9502
  ska-low-mccs-spshw:
    deviceServers:
      daqs:
        bandpass-daq-ci-1:
          low-mccs/bandpass-daq/ci-1:
            host: daqrx-ci-1-bandpass
            id: 1
            logging_level_default: 5
            port: 50051
            skuid_url: http://ska-ser-skuid-ska-ser-skuid-svc:9870/
        bandpass-daq-ci-2:
          low-mccs/bandpass-daq/ci-2:
            host: daqrx-ci-2-bandpass
            id: 2
            logging_level_default: 5
            port: 50051
            skuid_url: http://ska-ser-skuid-ska-ser-skuid-svc:9870/
        calibration-daq-ci-1:
          low-mccs/calibration-daq/ci-1:
            host: daqrx-ci-1-calibration
            id: 1
            logging_level_default: 5
            port: 50051
            skuid_url: http://ska-ser-skuid-ska-ser-skuid-svc:9870/
        calibration-daq-ci-2:
          low-mccs/calibration-daq/ci-2:
            host: daqrx-ci-2-calibration
            id: 2
            logging_level_default: 5
            port: 50051
            skuid_url: http://ska-ser-skuid-ska-ser-skuid-svc:9870/
      spsstations:
        ci-1:
          low-mccs/spsstation/ci-1:
            antenna_config_uri: []
            daq_trl: low-mccs/calibration-daq/ci-1
            logging_level_default: 5
            sdn_first_interface: 10.0.0.128/16
            station_id: 1
            subracks:
            - low-mccs/subrack/ci-1-sr1
            tpms:
            - low-mccs/tile/ci-1-tpm01
        ci-2:
          low-mccs/spsstation/ci-2:
            antenna_config_uri: []
            daq_trl: low-mccs/calibration-daq/ci-2
            logging_level_default: 5
            sdn_first_interface: 10.0.0.192/16
            station_id: 2
            subracks:
            - low-mccs/subrack/ci-2-sr1
            tpms:
            - low-mccs/tile/ci-2-tpm01
      subracks:
        ci-1-sr1:
          low-mccs/subrack/ci-1-sr1:
            logging_level_default: 5
            srmb_host: subrack-simulator-ci-1-sr1
            srmb_port: 8081
        ci-2-sr1:
          low-mccs/subrack/ci-2-sr1:
            logging_level_default: 5
            srmb_host: subrack-simulator-ci-2-sr1
            srmb_port: 8081
      tpms:
        ci-1-tpm01:
          low-mccs/tile/ci-1-tpm01:
            host: 10.0.10.201
            logging_level_default: 5
            port: 10000
            simulation_config: 1
            station_id: 1
            subrack: ci-1-sr1
            subrack_slot: 1
            test_config: 1
            tile_id: 0
            version: tpm_v1_6
        ci-2-tpm01:
          low-mccs/tile/ci-2-tpm01:
            host: 10.0.10.201
            logging_level_default: 5
            port: 10000
            simulation_config: 1
            station_id: 2
            subrack: ci-2-sr1
            subrack_slot: 1
            test_config: 1
            tile_id: 0
            version: tpm_v1_6
    simulators:
      subracks:
        ci-1-sr1:
          srmb_host: subrack-simulator-ci-1-sr1
          srmb_port: 8081
        ci-2-sr1:
          srmb_host: subrack-simulator-ci-2-sr1
          srmb_port: 8081
    ska-low-mccs-daq:
      receivers:
        ci-1-bandpass:
          affinity: null
          expose_data_service: true
          grpc_port: 50051
          node_selector: null
          nvidia_gpu: false
          receiver_interface: eth0
          receiver_port: 4660
          tolerations: null
        ci-1-calibration:
          affinity: null
          grpc_port: 50051
          node_selector: null
          nvidia_gpu: false
          receiver_interface: eth0
          receiver_port: 4660
          storage: daq-data
          tolerations: null
        ci-2-bandpass:
          affinity: null
          expose_data_service: true
          grpc_port: 50051
          node_selector: null
          nvidia_gpu: false
          receiver_interface: eth0
          receiver_port: 4660
          tolerations: null
        ci-2-calibration:
          affinity: null
          grpc_port: 50051
          node_selector: null
          nvidia_gpu: false
          receiver_interface: eth0
          receiver_port: 4660
          storage: daq-data
          tolerations: null
      storage:
        daq-data:
          size: 250Mi
          storage_class: nfss1

ska-sdp:
  enabled: false


ska-low-cbf:
  enabled: false

ska-pst-lmc:
  enabled: false

ska-pst:
  enabled: false

ska-csp-lmc-low:
  enabled : false
  
ska-ser-skuid:
  enabled : false


ska-low-cbf-proc:
  enabled: false
